# Generated by Django 5.2.3 on 2025-07-07 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InformationGathering', '0015_zoomeyeinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasscanScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('ports', models.JSONField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], default='Success', max_length=50)),
                ('raw_output', models.TextField(blank=True, null=True)),
                ('scan_flags', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masscan_scans', to='InformationGathering.target')),
            ],
        ),
    ]
