# Generated by Django 5.2 on 2025-08-02 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InformationGathering', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedNmapScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('scan_output', models.JSONField()),
                ('scan_flags', models.JSONField()),
                ('scan_duration', models.FloatField(blank=True, null=True)),
                ('open_ports', models.JSONField(default=list)),
                ('filtered_ports', models.JSONField(default=list)),
                ('service_versions', models.JSONField(default=list)),
                ('os_details', models.JSONField(default=dict)),
                ('host_uptime', models.CharField(blank=True, max_length=100, null=True)),
                ('traceroute', models.JSONField(blank=True, null=True)),
                ('scripts_output', models.JSONField(default=dict)),
                ('vulnerabilities', models.JSONField(default=list)),
                ('protocols_detected', models.JSONField(default=list)),
                ('ports_scanned', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=0)),
                ('errors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformationGathering.target')),
            ],
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('masscan', 'Masscan'), ('nmap', 'Nmap')], max_length=50)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], default='Success', max_length=50)),
                ('raw_output', models.TextField(blank=True, null=True)),
                ('open_ports', models.JSONField(blank=True, null=True)),
                ('scan_flags', models.JSONField(blank=True, null=True)),
                ('responders', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='InformationGathering.target')),
            ],
        ),
    ]
