# Generated by Django 5.2.3 on 2025-07-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scanning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masscanscan',
            old_name='ports',
            new_name='open_ports',
        ),
    ]
