# Generated by Django 5.2.3 on 2025-07-18 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationGathering', '0015_zoomeyeinfo'),
        ('Scanning', '0003_scanresult_delete_masscanscan'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedNmapScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('scan_output', models.JSONField()),
                ('scan_flags', models.JSONField()),
                ('scan_duration', models.FloatField(blank=True, null=True)),
                ('open_ports', models.JSONField(default=list)),
                ('filtered_ports', models.JSONField(default=list)),
                ('service_versions', models.JSONField(default=list)),
                ('os_details', models.JSONField(default=dict)),
                ('host_uptime', models.CharField(blank=True, max_length=100, null=True)),
                ('traceroute', models.JSONField(blank=True, null=True)),
                ('scripts_output', models.JSONField(default=dict)),
                ('vulnerabilities', models.JSONField(default=list)),
                ('protocols_detected', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformationGathering.target')),
            ],
        ),
    ]
