# Generated by Django 5.2.3 on 2025-07-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scanning', '0004_advancednmapscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancednmapscan',
            name='errors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='advancednmapscan',
            name='ports_scanned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advancednmapscan',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
