# Generated by Django 5.2.3 on 2025-07-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedEnumResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('os_info', models.TextField(blank=True)),
                ('open_ports', models.JSONField(default=dict)),
                ('smb_info', models.TextField(blank=True)),
                ('enum4linux_output', models.TextField(blank=True)),
                ('rpc_output', models.TextField(blank=True)),
                ('netbios_info', models.TextField(blank=True)),
                ('snmp_info', models.TextField(blank=True)),
                ('ldap_info', models.TextField(blank=True)),
                ('dns_zone_transfer', models.TextField(blank=True)),
                ('hidden_dirs', models.TextField(blank=True)),
                ('tools_used', models.CharField(blank=True, max_length=300)),
                ('raw_output', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnumerationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('smb_shares', models.TextField(blank=True, null=True)),
                ('users_groups', models.TextField(blank=True, null=True)),
                ('services_banners', models.TextField(blank=True, null=True)),
                ('rpc_info', models.TextField(blank=True, null=True)),
                ('netbios_info', models.TextField(blank=True, null=True)),
                ('snmp_data', models.TextField(blank=True, null=True)),
                ('ldap_data', models.TextField(blank=True, null=True)),
                ('os_info', models.JSONField(blank=True, null=True)),
                ('hidden_web_content', models.TextField(blank=True, null=True)),
                ('tools_used', models.CharField(help_text='Comma-separated tools used (e.g. enum4linux, nmap, dirsearch)', max_length=300)),
                ('raw_output', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
