# Generated by Django 5.2.3 on 2025-07-23 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enumeration', '0001_initial'),
        ('InformationGathering', '0015_zoomeyeinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancedenumresult',
            name='raw_output',
        ),
        migrations.RemoveField(
            model_name='advancedenumresult',
            name='tools_used',
        ),
        migrations.AlterField(
            model_name='advancedenumresult',
            name='target',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='advancedenumresult',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='enumerationresult',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enumeration_results', to='InformationGathering.target'),
        ),
        migrations.AlterField(
            model_name='enumerationresult',
            name='tools_used',
            field=models.CharField(help_text='Comma-separated tools used (e.g. enum4linux, nmap, nessus, nikto-ng)', max_length=300),
        ),
    ]
