# Generated by Django 5.1.7 on 2025-04-18 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('host', models.GenericIPAddressField()),
                ('type', models.CharField(max_length=50)),
                ('is_local', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IPInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('asn', models.CharField(blank=True, max_length=50, null=True)),
                ('asn_registry', models.CharField(blank=True, max_length=100, null=True)),
                ('asn_cidr', models.CharField(blank=True, max_length=100, null=True)),
                ('asn_country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('asn_date', models.DateField(blank=True, null=True)),
                ('asn_description', models.TextField(blank=True, null=True)),
                ('network_name', models.CharField(blank=True, max_length=255, null=True)),
                ('network_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('network_status', models.CharField(blank=True, max_length=50, null=True)),
                ('network_start_address', models.GenericIPAddressField(blank=True, null=True)),
                ('network_end_address', models.GenericIPAddressField(blank=True, null=True)),
                ('network_cidr', models.CharField(blank=True, max_length=100, null=True)),
                ('network_type', models.CharField(blank=True, max_length=100, null=True)),
                ('network_parent_handle', models.CharField(blank=True, max_length=50, null=True)),
                ('org_name', models.CharField(blank=True, max_length=255, null=True)),
                ('org_street', models.CharField(blank=True, max_length=255, null=True)),
                ('org_city', models.CharField(blank=True, max_length=100, null=True)),
                ('org_state', models.CharField(blank=True, max_length=100, null=True)),
                ('org_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('org_country', models.CharField(blank=True, max_length=100, null=True)),
                ('abuse_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('abuse_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('abuse_contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('admin_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('noc_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('noc_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('noc_contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('abuse_report_link', models.URLField(blank=True, null=True)),
                ('whois_info_link', models.URLField(blank=True, null=True)),
                ('terms_of_service_link', models.URLField(blank=True, null=True)),
                ('geofeed_link', models.URLField(blank=True, null=True)),
                ('network_ip_version', models.CharField(blank=True, max_length=10, null=True)),
                ('admin_contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_info', to='InformationGathering.target')),
            ],
        ),
        migrations.CreateModel(
            name='WhoisInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('registrar', models.CharField(blank=True, max_length=255, null=True)),
                ('whois_server', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_url', models.URLField(blank=True, null=True)),
                ('updated_date', models.JSONField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('name_servers', models.JSONField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('emails', models.JSONField(blank=True, null=True)),
                ('dnssec', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('org', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('registrant_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='InformationGathering.target')),
            ],
        ),
    ]
