# Generated by Django 5.2 on 2025-04-30 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationGathering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NmapScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('scan_type', models.CharField(choices=[('TCP', 'TCP Scan'), ('UDP', 'UDP Scan'), ('SYN', 'SYN Scan'), ('Full', 'Full Scan')], max_length=50)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], max_length=50)),
                ('scan_output', models.TextField(blank=True, null=True)),
                ('scan_duration', models.FloatField(blank=True, null=True)),
                ('scan_flags', models.JSONField(blank=True, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nmap_scans', to='InformationGathering.target')),
            ],
        ),
        migrations.CreateModel(
            name='NmapScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.GenericIPAddressField()),
                ('host_status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('unreachable', 'Unreachable')], max_length=50)),
                ('host_name', models.CharField(blank=True, max_length=255, null=True)),
                ('host_os', models.CharField(blank=True, max_length=255, null=True)),
                ('os_detection_method', models.CharField(blank=True, max_length=100, null=True)),
                ('os_accuracy', models.IntegerField(blank=True, null=True)),
                ('host_fqdn', models.CharField(blank=True, max_length=255, null=True)),
                ('is_vpn', models.BooleanField(default=False)),
                ('nmap_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='InformationGathering.nmapscan')),
            ],
        ),
        migrations.CreateModel(
            name='OpenPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('protocol', models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP')], max_length=10)),
                ('service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('service_version', models.CharField(blank=True, max_length=255, null=True)),
                ('service_method', models.CharField(choices=[('banner', 'Banner Grabbing'), ('fingerprint', 'Fingerprinting'), ('none', 'None')], default='none', max_length=50)),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('filtered', 'Filtered')], max_length=50)),
                ('nmap_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_ports', to='InformationGathering.nmapscan')),
            ],
        ),
    ]
