# Generated by Django 4.2.20 on 2025-03-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationGathering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('host', models.GenericIPAddressField()),
                ('type', models.CharField(max_length=50)),
                ('is_local', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
