# Generated by Django 5.2 on 2025-04-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationGathering', '0002_nmapscan_nmapscanresult_openport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openport',
            name='nmap_scan',
        ),
        migrations.AddField(
            model_name='nmapscan',
            name='host_os',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nmapscan',
            name='is_vpn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nmapscan',
            name='open_ports',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nmapscan',
            name='os_accuracy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nmapscan',
            name='os_detection_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nmapscan',
            name='results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='NmapScanResult',
        ),
        migrations.DeleteModel(
            name='OpenPort',
        ),
    ]
