# Generated by Django 5.1.7 on 2025-04-04 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationGathering', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='WhoisInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('registrar', models.CharField(blank=True, max_length=255, null=True)),
                ('whois_server', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_url', models.URLField(blank=True, null=True)),
                ('updated_date', models.JSONField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('name_servers', models.JSONField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('emails', models.JSONField(blank=True, null=True)),
                ('dnssec', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('org', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('registrant_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whois_info', to='InformationGathering.target')),
            ],
        ),
    ]
