# Generated by Django 5.2 on 2025-04-30 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationGathering', '0003_remove_openport_nmap_scan_nmapscan_host_os_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShodanInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('ip_str', models.GenericIPAddressField()),
                ('org', models.CharField(blank=True, max_length=255, null=True)),
                ('os', models.CharField(blank=True, max_length=255, null=True)),
                ('isp', models.CharField(blank=True, max_length=255, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('ports', models.JSONField(blank=True, null=True)),
                ('services', models.JSONField(blank=True, null=True)),
                ('vulnerabilities', models.JSONField(blank=True, null=True)),
                ('ssl_issuer', models.CharField(blank=True, max_length=255, null=True)),
                ('ssl_subject', models.TextField(blank=True, null=True)),
                ('ssl_not_before', models.DateTimeField(blank=True, null=True)),
                ('ssl_not_after', models.DateTimeField(blank=True, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shodan_scans', to='InformationGathering.target')),
            ],
        ),
    ]
