# Generated by Django 5.2 on 2025-04-08 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationGathering', '0004_alter_user_username_whoisinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('asn', models.CharField(blank=True, max_length=50, null=True)),
                ('asn_registry', models.CharField(blank=True, max_length=100, null=True)),
                ('asn_cidr', models.CharField(blank=True, max_length=100, null=True)),
                ('asn_country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('asn_date', models.DateField(blank=True, null=True)),
                ('asn_description', models.TextField(blank=True, null=True)),
                ('network_name', models.CharField(blank=True, max_length=255, null=True)),
                ('network_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('network_status', models.CharField(blank=True, max_length=50, null=True)),
                ('network_start_address', models.GenericIPAddressField(blank=True, null=True)),
                ('network_end_address', models.GenericIPAddressField(blank=True, null=True)),
                ('network_cidr', models.CharField(blank=True, max_length=100, null=True)),
                ('network_type', models.CharField(blank=True, max_length=100, null=True)),
                ('network_parent_handle', models.CharField(blank=True, max_length=50, null=True)),
                ('org_name', models.CharField(blank=True, max_length=255, null=True)),
                ('org_street', models.CharField(blank=True, max_length=255, null=True)),
                ('org_city', models.CharField(blank=True, max_length=100, null=True)),
                ('org_state', models.CharField(blank=True, max_length=100, null=True)),
                ('org_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('org_country', models.CharField(blank=True, max_length=100, null=True)),
                ('abuse_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('abuse_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('abuse_contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('admin_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('noc_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('noc_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('noc_contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('abuse_report_link', models.URLField(blank=True, null=True)),
                ('whois_info_link', models.URLField(blank=True, null=True)),
                ('terms_of_service_link', models.URLField(blank=True, null=True)),
                ('geofeed_link', models.URLField(blank=True, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_info', to='InformationGathering.target')),
            ],
        ),
    ]
