# Generated by Django 5.2 on 2025-05-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationGathering', '0005_censysinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shodaninfo',
            name='asn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shodaninfo',
            name='cf_cache_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shodaninfo',
            name='cf_ray',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shodaninfo',
            name='domains',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shodaninfo',
            name='hostnames',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shodaninfo',
            name='server_timing',
            field=models.TextField(blank=True, null=True),
        ),
    ]
