# Generated by Django 5.2 on 2025-04-18 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationGathering', '0005_ipinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipinfo',
            name='admin_contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ipinfo',
            name='network_ip_version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='whoisinfo',
            name='target',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='InformationGathering.target'),
        ),
    ]
