# Generated by Django 5.2 on 2025-05-06 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationGathering', '0006_shodaninfo_asn_shodaninfo_cf_cache_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shodaninfo',
            old_name='ip_str',
            new_name='ip',
        ),
        migrations.RenameField(
            model_name='shodaninfo',
            old_name='cf_ray',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='shodaninfo',
            old_name='scan_date',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='shodaninfo',
            name='cf_cache_status',
        ),
        migrations.RemoveField(
            model_name='shodaninfo',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='shodaninfo',
            name='domains',
        ),
        migrations.RemoveField(
            model_name='shodaninfo',
            name='hostnames',
        ),
        migrations.RemoveField(
            model_name='shodaninfo',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='shodaninfo',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='shodaninfo',
            name='org',
        ),
        migrations.RemoveField(
            model_name='shodaninfo',
            name='ports',
        ),
        migrations.RemoveField(
            model_name='shodaninfo',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='shodaninfo',
            name='server_timing',
        ),
        migrations.RemoveField(
            model_name='shodaninfo',
            name='ssl_issuer',
        ),
        migrations.RemoveField(
            model_name='shodaninfo',
            name='ssl_not_after',
        ),
        migrations.RemoveField(
            model_name='shodaninfo',
            name='ssl_not_before',
        ),
        migrations.RemoveField(
            model_name='shodaninfo',
            name='ssl_subject',
        ),
        migrations.RemoveField(
            model_name='shodaninfo',
            name='vulnerabilities',
        ),
        migrations.AddField(
            model_name='shodaninfo',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shodaninfo',
            name='open_ports',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='shodaninfo',
            name='os',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shodaninfo',
            name='services',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='shodaninfo',
            name='target',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shodan_info', to='InformationGathering.target'),
        ),
    ]
