# Generated by Django 5.2 on 2025-05-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationGathering', '0007_rename_ip_str_shodaninfo_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shodaninfo',
            name='domains',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shodaninfo',
            name='hostnames',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shodaninfo',
            name='last_update',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shodaninfo',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shodaninfo',
            name='vulnerabilities',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
