# Generated by Django 5.2 on 2025-05-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationGathering', '0008_shodaninfo_domains_shodaninfo_hostnames_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='censysinfo',
            name='collection_status',
            field=models.CharField(default='success', max_length=50),
        ),
    ]
