# Generated by Django 5.2 on 2025-05-10 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationGathering', '0011_zmapscan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSonarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=50)),
                ('entry_count', models.IntegerField()),
                ('data', models.JSONField()),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformationGathering.target')),
            ],
        ),
    ]
