# Generated by Django 5.2 on 2025-05-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationGathering', '0012_projectsonardata'),
    ]

    operations = [
        migrations.AddField(
            model_name='censysinfo',
            name='domains',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censysinfo',
            name='hostnames',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censysinfo',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censysinfo',
            name='vulnerabilities',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
