# Generated by Django 5.2 on 2025-05-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationGathering', '0013_censysinfo_domains_censysinfo_hostnames_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censysinfo',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
