# Generated by Django 5.2 on 2025-05-26 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationGathering', '0014_alter_censysinfo_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomEyeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField()),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('isp', models.CharField(blank=True, max_length=255, null=True)),
                ('asn', models.CharField(blank=True, max_length=100, null=True)),
                ('org', models.CharField(blank=True, max_length=255, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('hostnames', models.JSONField(blank=True, null=True)),
                ('domains', models.JSONField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('open_ports', models.JSONField(blank=True, null=True)),
                ('services', models.JSONField(blank=True, null=True)),
                ('vulnerabilities', models.JSONField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoomeye_scans', to='InformationGathering.target')),
            ],
        ),
    ]
